### ISSUE TITLE
lineplot extreme edge case returns non-array for data.seriesY

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#144]
When a very large bin width is provided to the back end, and a single bin's worth of data is returned, seriesY is a scalar, instead of an array.

I realise that in general usage, the back end recommends binSlider values that give at least two bins, but there are scenarios where the user changes from months to years and the year-based constraints are unknown at the time the request is made.

e.g. GEMS1 - Birth date, bin on months and max the slider to 49. Then switch to year. 

```
{
	"data": [
		{
			"seriesX": [
				"2003-01-01 - 2052-01-01"
			],
			"seriesY": "2.8457",
			"binSampleSize": [
				{
					"N": 9436
				}
			],
			"binStart": [
				"2003-01-01T00:00:00"
			],
			"binEnd": [
				"2052-01-01T00:00:00"
			]
		}
	]
}
```

**Comment by asizemore** [comment]
Addressed by #149 . Closing.

**Comment by nkittur-uga** [comment]
Tried this in GEMS1 and I am unfortunately still getting the big pink error. 
![Screen Shot 2022-04-12 at 2 01 55 PM (2)](https://user-images.githubusercontent.com/67710160/163025401-2aa9e0fd-23f8-451c-9d7a-dd789d6d3925.png)

**Comment by d-callan** [comment]
There was an issue w deploying some backend services which was very recently (last 5-10 min) resolved. Could you try again please?

**Comment by nkittur-uga** [comment]
No errors now. Passes QA.
