### ISSUE TITLE
Mosaic plot (2x2) - statistics tab backend 1

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/plot.data#202]
related to https://github.com/VEuPathDB/web-eda/issues/1384

Mockups: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=317%3A623&t=ZCxlWaPOOG1AbgKr-0

We will need to calculate the following statistics to roll out in b62:

1. Chi-squared
2. Fischer's exact test
3. Prevalence
4. Odds Ratio
5. Risk Ratio

Additional "nice to have" stats to roll out for b62 can be found in this ticket: https://github.com/VEuPathDB/plot.data/issues/203

**Comment by nkittur-uga** [comment]
This ticket will be QAed once the front-end tickets are implemented.

**Comment by danicahelb** [comment]
**Please check & fix calculations for:**
- Odds ratio 95% CI
- Risk ratio point estimate
- Risk ration 95% CI

_More info:_ 

I've hand checked the calculation for Odds ratio and Risk ratio, using the formulas in our more information dropdown.
- Odds ratio = 5.63
- Risk ratio = 2.04

I get the same numbers as this calculator: http://vassarstats.net/odds2x2.html
- The point estimate for Odds ratio is correct, but the 95% CI for the Odds ratio does not match what the calculator gives us.
- The point estimate for the risk ratio is incorrect and its 95% CI is also incorrect

<img width="704" alt="image" src="https://user-images.githubusercontent.com/25450900/222222171-7da3adb3-6780-4803-8534-0fc225883351.png">

**Comment by d-callan** [comment]
thanks for the detailed report, really helped hunt this down and it was super subtle!

should be fixed w rserve v5.1.3

**Comment by danicahelb** [comment]
Hey @d-callan, I just checked and I am still getting the exact same stats table


![Image](https://user-images.githubusercontent.com/25450900/223193305-2667bb51-e37e-414d-9816-d3f5596836d7.png)

**Comment by d-callan** [comment]
@dmfalke tagger still says v5.1.2 for rserve. i dont think this was actually deployed.

**Comment by danicahelb** [comment]
point estimates are now correct for Odds ratio & risk ratio. But I still don't understand what is going on with the 95% CI. 

![Image](https://user-images.githubusercontent.com/25450900/223270648-4bca352a-f46e-42d9-a5f3-5315c15a94c9.png)

**Comment by danicahelb** [comment]
also, for Chi-square the 95% CI should just say `n/a` instead of `(NA-NA)`. Do i need to make a separate front-end ticket for this?

**Comment by d-callan** [comment]
I'll look into the NAs in the CIs. I don't think it requires a frontend ticket at this point.

**Comment by d-callan** [comment]
so i just pushed a fix for the CIs for odds ratio and relative risk. i can work on the (NA-NA) bit next. @danicahelb you want to qa that now or when i have the chisq CI sorted as well?

**Comment by danicahelb** [comment]
It looks so much better, thanks @d-callan!

The http://vassarstats.net/odds2x2.html calculator is showing risk ratio as 2.04 (1.99-2.10)...so slightly different 95% CI. Any idea why this could be?


![Image](https://user-images.githubusercontent.com/25450900/223787465-ae5623c9-d2d3-4096-bba4-bde9ec0ed701.png)

**Comment by d-callan** [comment]
yea actually.. ill bet i found the CIs after rounding the point est to 2 signifs rather than before. ill fix that in a bit

**Comment by danicahelb** [comment]
We would like p-values for Odds Ratio & Risk Ratio. If we don't have enough time to include this for b62, it is ok to go out in b63. I made this ticket: https://github.com/VEuPathDB/EdaNewIssues/issues/599

**Comment by nkittur-uga** [comment]
1. The risk ratio looks incorrect! 
2. The chi square is close enough
3. Fisher's exact test should not really be calculated with a sample size so big
<img width="781" alt="Screenshot 2023-03-08 at 1 01 16 PM" src="https://user-images.githubusercontent.com/67710160/223794059-6e0537a5-111b-458d-a86b-968185f2c27f.png">

**Comment by d-callan** [comment]
my understanding was to calculate both chisq and fisher and let the user look to one or the other as appropriate. i think if we mean to change that, we should have at least a brief discussion to know everyone is ok w that and what a reasonable cutoff should be for showing one vs another. i dont think thats something i can change for b62 at this point.

**Comment by nkittur-uga** [comment]
Fine to leave chisq and fisher as they are for this build! Thanks!

**Comment by d-callan** [comment]
@danicahelb i updated the calculation for CIs, but theyre still so close to what they were before that after rounding you wont actually see the difference on the site, at least for this ex. which means there is still a discrepancy. ive tried to look through the site you linked for documentation that might say how they find the CIs to see what were doing differently, but ive had no luck. if you know the site well, maybe you know where to find that documentation?

**Comment by danicahelb** [comment]
@d-callan i don't. i just randomly looked up a calculator to double check our stats

**Comment by danicahelb** [comment]
@nkittur-uga that vassar site sets up the 2x2 tables in a weird way. I double checked using this calculator: https://www.medcalc.org/calc/relative_risk.php and danielle's calculations for risk ratio look good.


![Image](https://user-images.githubusercontent.com/25450900/223842187-f4226886-ed12-4dd8-82fa-32b134969e84.png)


@d-callan that site linked here gives documentation for how they are calculating their 95% CI (and give the same 95% CI as I was getting from the vassar site).


![Image](https://user-images.githubusercontent.com/25450900/223842286-82330fae-06a9-41c3-b391-d0141e28a8da.png)

**Comment by d-callan** [comment]
found it. had some signs wrong for the standard error.

**Comment by danicahelb** [comment]
@d-callan thanks! stats look great!


![Image](https://user-images.githubusercontent.com/25450900/224182777-b6065407-362e-4be2-9279-e68a2b0bf424.png)
